"""Command modules split from legacy core handler."""

from .read_only_decompile import (
    decompile_function,
    disassemble_function,
    disassemble_range,
    get_callee,
)
from .read_only_functions import (
    get_function_by_address,
    list_classes,
    list_functions,
    search_functions_by_name,
)
from .read_only_memory_data import (
    get_bytes,
    get_data_by_label,
    get_enum,
    get_struct,
    list_data_items,
    list_exports,
    list_imports,
    list_namespaces,
    list_segments,
    list_strings,
    search_bytes,
)
from .read_only_xrefs import (
    get_function_xrefs,
    get_xrefs_from,
    get_xrefs_to,
)
from .mutating_symbols import (
    add_bookmark,
    analyze_program,
    create_function,
    delete_bookmark,
    delete_function,
    list_bookmarks,
    reanalyze_program,
    rename_data,
    rename_function,
    rename_variable,
    set_bytes,
    set_decompiler_comment,
    set_disassembly_comment,
    set_function_prototype,
    set_local_variable_type,
)
from .mutating_data_types import (
    add_struct_members,
    clear_struct,
    create_struct,
    delete_struct,
    list_data_types,
    remove_struct_members,
    rename_data_type,
    set_global_data_type,
)

__all__ = [
    "decompile_function",
    "disassemble_function",
    "disassemble_range",
    "get_callee",
    "get_xrefs_to",
    "get_xrefs_from",
    "get_function_xrefs",
    "list_segments",
    "list_imports",
    "list_exports",
    "list_namespaces",
    "list_data_items",
    "list_strings",
    "get_data_by_label",
    "get_bytes",
    "search_bytes",
    "get_struct",
    "get_enum",
    "rename_function",
    "rename_data",
    "rename_variable",
    "set_decompiler_comment",
    "set_disassembly_comment",
    "set_function_prototype",
    "set_local_variable_type",
    "create_struct",
    "add_struct_members",
    "clear_struct",
    "delete_struct",
    "rename_data_type",
    "list_data_types",
    "remove_struct_members",
    "set_global_data_type",
    "set_bytes",
    "add_bookmark",
    "list_bookmarks",
    "delete_bookmark",
    "create_function",
    "delete_function",
    "analyze_program",
    "reanalyze_program",
    "list_functions",
    "list_classes",
    "search_functions_by_name",
    "get_function_by_address",
]
