"""Declarative registry for core command shim wiring."""

from __future__ import absolute_import, print_function

from ghidra_headless.handlers.commands import (
    add_bookmark,
    add_struct_members,
    analyze_program,
    bsim_apply_matches,
    bsim_query_function,
    bsim_query_target,
    bsim_register_target,
    bsim_update_target_signatures,
    bsim_validate_match,
    create_enum,
    create_function,
    create_label,
    create_struct,
    decompile_function,
    delete_bookmark,
    delete_data_type,
    delete_function,
    export_program,
    get_bytes,
    get_comments,
    get_data_by_label,
    get_function,
    get_program_info,
    list_bookmarks,
    list_data_items,
    list_data_types,
    list_exports,
    list_functions,
    list_imports,
    list_namespaces,
    list_segments,
    list_strings,
    parse_c_declarations,
    redo_program_change,
    remove_struct_members,
    rename_data,
    rename_data_type,
    rename_function,
    rename_variable,
    search_bytes,
    search_symbols,
    set_bytes,
    set_comment,
    set_enum_values,
    set_function_prototype,
    set_global_data_type,
    set_local_variable_type,
    undo_program_change,
)
from ghidra_headless.handlers.commands.analysis_queries import disassemble, get_call_edges, get_data_type, get_xrefs
from ghidra_headless.handlers.commands.batch_edits import apply_edits
from ghidra_headless.handlers.commands.batch_read import batch_read
from ghidra_headless.handlers.commands.scripts import run_script

COMMAND_NAMES = (
    "batch_read",
    "get_xrefs",
    "get_call_edges",
    "disassemble",
    "get_data_type",
    "apply_edits",
    "bsim_validate_match",
    "list_functions",
    "decompile_function",
    "rename_function",
    "rename_data",
    "list_segments",
    "list_imports",
    "list_exports",
    "list_namespaces",
    "list_data_items",
    "rename_variable",
    "get_function",
    "set_function_prototype",
    "set_local_variable_type",
    "list_strings",
    "create_struct",
    "add_struct_members",
    "list_data_types",
    "get_data_by_label",
    "get_bytes",
    "search_bytes",
    "rename_data_type",
    "set_global_data_type",
    "remove_struct_members",
    "set_bytes",
    "add_bookmark",
    "list_bookmarks",
    "delete_bookmark",
    "create_function",
    "delete_function",
    "analyze_program",
    "set_comment",
    "delete_data_type",
    "get_program_info",
    "get_comments",
    "search_symbols",
    "create_label",
    "undo_program_change",
    "redo_program_change",
    "create_enum",
    "set_enum_values",
    "parse_c_declarations",
    "export_program",
    "bsim_query_target",
    "bsim_query_function",
    "bsim_register_target",
    "bsim_apply_matches",
    "bsim_update_target_signatures",
    "run_script",
)

INTERNAL_COMMAND_NAMES = (
    # Annotation primitives used by apply_edits; not standalone MCP tools.
    "rename_function",
    "rename_data",
    "rename_variable",
    "set_comment",
    "bsim_validate_match",
    # export_program is exposed through the registry so the path policy runs first.
    "export_program",
    "bsim_query_target",
    "bsim_query_function",
    "bsim_register_target",
    "bsim_apply_matches",
    "bsim_update_target_signatures",
    # run_script is exposed through the registry so the script service gates it first.
    "run_script",
)

COMMAND_TO_IMPL = {
    "batch_read": batch_read,
    "get_xrefs": get_xrefs,
    "get_call_edges": get_call_edges,
    "disassemble": disassemble,
    "get_data_type": get_data_type,
    "apply_edits": apply_edits,
    "bsim_validate_match": bsim_validate_match,
    "list_functions": list_functions,
    "decompile_function": decompile_function,
    "rename_function": rename_function,
    "rename_data": rename_data,
    "list_segments": list_segments,
    "list_imports": list_imports,
    "list_exports": list_exports,
    "list_namespaces": list_namespaces,
    "list_data_items": list_data_items,
    "rename_variable": rename_variable,
    "get_function": get_function,
    "set_function_prototype": set_function_prototype,
    "set_local_variable_type": set_local_variable_type,
    "list_strings": list_strings,
    "create_struct": create_struct,
    "add_struct_members": add_struct_members,
    "list_data_types": list_data_types,
    "get_data_by_label": get_data_by_label,
    "get_bytes": get_bytes,
    "search_bytes": search_bytes,
    "rename_data_type": rename_data_type,
    "set_global_data_type": set_global_data_type,
    "remove_struct_members": remove_struct_members,
    "set_bytes": set_bytes,
    "add_bookmark": add_bookmark,
    "list_bookmarks": list_bookmarks,
    "delete_bookmark": delete_bookmark,
    "create_function": create_function,
    "delete_function": delete_function,
    "analyze_program": analyze_program,
    "set_comment": set_comment,
    "delete_data_type": delete_data_type,
    "get_program_info": get_program_info,
    "get_comments": get_comments,
    "search_symbols": search_symbols,
    "create_label": create_label,
    "undo_program_change": undo_program_change,
    "redo_program_change": redo_program_change,
    "create_enum": create_enum,
    "set_enum_values": set_enum_values,
    "parse_c_declarations": parse_c_declarations,
    "export_program": export_program,
    "bsim_query_target": bsim_query_target,
    "bsim_query_function": bsim_query_function,
    "bsim_register_target": bsim_register_target,
    "bsim_apply_matches": bsim_apply_matches,
    "bsim_update_target_signatures": bsim_update_target_signatures,
    "run_script": run_script,
}

# command -> dependency profile for keyword argument injection into command impl.
COMMAND_PROFILE = {
    "batch_read": ("ensure_context", "execute_read"),
    "get_xrefs": ("ensure_context", "get_address", "iter_items"),
    "get_call_edges": ("ensure_context", "get_address", "find_function_by_name", "iter_items"),
    "disassemble": ("ensure_context", "get_address", "find_function_by_name", "iter_items", "comment_types"),
    "get_data_type": (
        "ensure_context",
        "dt_manager",
        "find_data_type_by_name",
        "describe_data_type",
        "describe_struct",
        "describe_enum",
    ),
    "apply_edits": (
        "ensure_context",
        "execute_edit",
        "get_address",
        "decompile_high_function",
        "iter_items",
        "comment_types",
    ),
    "bsim_validate_match": ("ensure_context", "get_address"),
    "list_functions": ("ensure_context", "to_int", "collect", "iter_items", "source_type"),
    "decompile_function": ("ensure_context", "get_address", "find_function_by_name", "decompile_function_object"),
    "rename_function": ("ensure_context", "get_address", "find_function_by_name", "txn", "source_type"),
    "rename_data": ("ensure_context", "get_address", "txn", "source_type"),
    "list_segments": ("ensure_context", "to_int"),
    "list_imports": ("ensure_context", "to_int"),
    "list_exports": ("ensure_context", "to_int", "iter_items", "is_exported_symbol"),
    "list_namespaces": ("ensure_context", "to_int", "iter_namespaces", "safe_call"),
    "list_data_items": ("ensure_context", "to_int"),
    "rename_variable": (
        "ensure_context",
        "get_address",
        "find_function_by_name",
        "decompile_high_function",
        "requires_full_param_commit",
        "high_function_db_util",
        "txn",
        "source_type",
    ),
    "get_function": ("ensure_context", "get_address", "find_function_by_name", "safe_call", "iter_items"),
    "set_function_prototype": (
        "ensure_context",
        "get_address",
        "find_function_by_name",
        "build_signature_parser",
        "safe_call",
        "apply_function_signature_cmd",
        "txn",
        "source_type",
    ),
    "set_local_variable_type": (
        "ensure_context",
        "get_address",
        "find_function_by_name",
        "parse_data_type",
        "decompile_high_function",
        "requires_full_param_commit",
        "high_function_db_util",
        "txn",
        "source_type",
    ),
    "list_strings": ("ensure_context", "to_int"),
    "create_struct": (
        "ensure_context",
        "to_int",
        "txn",
        "dt_manager",
        "category_path",
        "structure_data_type",
        "parse_data_type",
        "component_length",
        "describe_struct",
    ),
    "add_struct_members": (
        "ensure_context",
        "txn",
        "get_struct_datatype",
        "parse_data_type",
        "component_length",
        "dt_manager",
        "describe_struct",
    ),
    "list_data_types": (
        "ensure_context",
        "to_int",
        "dt_manager",
        "collect",
        "iter_items",
        "safe_call",
        "describe_data_type",
    ),
    "get_data_by_label": ("ensure_context", "iter_items"),
    "get_bytes": ("ensure_context", "to_int", "get_address", "hexdump"),
    "search_bytes": ("ensure_context", "to_int", "decode_hex_bytes"),
    "rename_data_type": (
        "ensure_context",
        "txn",
        "dt_manager",
        "category_path",
        "find_data_type_by_name",
        "describe_data_type",
    ),
    "set_global_data_type": (
        "ensure_context",
        "to_int",
        "get_address",
        "parse_data_type",
        "parse_clear_data_mode",
        "txn",
        "data_utilities",
    ),
    "remove_struct_members": ("ensure_context", "txn", "get_struct_datatype", "dt_manager", "describe_struct"),
    "set_bytes": ("ensure_context", "get_address", "decode_hex_bytes", "txn"),
    "add_bookmark": ("ensure_context", "get_address", "txn"),
    "list_bookmarks": ("ensure_context", "get_address", "to_int", "collect", "iter_items"),
    "delete_bookmark": ("ensure_context", "get_address", "txn", "iter_items"),
    "create_function": ("ensure_context", "get_address", "txn"),
    "delete_function": ("ensure_context", "get_address", "txn"),
    "analyze_program": ("ensure_context", "analyze_program_impl"),
    "set_comment": ("ensure_context", "get_address", "txn", "comment_types"),
    "get_program_info": ("ensure_context", "safe_call", "iter_items"),
    "get_comments": ("ensure_context", "get_address", "comment_types"),
    "search_symbols": ("ensure_context", "to_int", "iter_items", "safe_call"),
    "create_label": ("ensure_context", "get_address", "txn", "source_type"),
    "undo_program_change": ("ensure_context", "safe_call", "iter_items"),
    "redo_program_change": ("ensure_context", "safe_call", "iter_items"),
    "create_enum": (
        "ensure_context",
        "to_int",
        "txn",
        "dt_manager",
        "category_path",
        "enum_data_type",
        "describe_enum",
    ),
    "set_enum_values": ("ensure_context", "txn", "get_enum_datatype", "describe_enum", "iter_items"),
    "parse_c_declarations": ("ensure_context", "txn", "dt_manager", "iter_items"),
    "export_program": ("ensure_context", "safe_call"),
    "delete_data_type": (
        "ensure_context",
        "txn",
        "dt_manager",
        "category_path",
        "find_data_type_by_name",
        "describe_data_type",
    ),
    "bsim_query_target": ("ensure_context",),
    "bsim_query_function": ("ensure_context", "get_address", "find_function_by_name"),
    "bsim_register_target": ("ensure_context", "txn"),
    "bsim_apply_matches": ("ensure_context", "get_address", "find_function_by_name", "txn", "source_type"),
    "bsim_update_target_signatures": ("ensure_context",),
    "run_script": ("ensure_context", "current_key"),
}


__all__ = [
    "COMMAND_NAMES",
    "INTERNAL_COMMAND_NAMES",
    "COMMAND_TO_IMPL",
    "COMMAND_PROFILE",
]
