"""Declarative registry for core command shim wiring."""

from __future__ import absolute_import, print_function

from ghidra_headless.handlers.commands import (
    add_bookmark,
    add_struct_members,
    analyze_program,
    bsim_query_function,
    bsim_query_target,
    bsim_register_target,
    bsim_set_target_metadata,
    clear_struct,
    create_function,
    create_struct,
    decompile_function,
    delete_bookmark,
    delete_function,
    delete_struct,
    disassemble_function,
    disassemble_range,
    get_bytes,
    get_callee,
    get_data_by_label,
    get_enum,
    get_function,
    get_function_xrefs,
    get_struct,
    get_xrefs_from,
    get_xrefs_to,
    list_classes,
    list_data_items,
    list_data_types,
    list_exports,
    list_functions,
    list_imports,
    list_bookmarks,
    list_namespaces,
    list_segments,
    list_strings,
    remove_struct_members,
    rename_data_type,
    reanalyze_program,
    rename_data,
    rename_function,
    rename_variable,
    search_bytes,
    search_functions_by_name,
    set_bytes,
    set_decompiler_comment,
    set_disassembly_comment,
    set_function_prototype,
    set_global_data_type,
    set_local_variable_type,
)

COMMAND_NAMES = (
    "list_functions",
    "list_classes",
    "decompile_function",
    "rename_function",
    "rename_data",
    "list_segments",
    "list_imports",
    "list_exports",
    "list_namespaces",
    "list_data_items",
    "search_functions_by_name",
    "rename_variable",
    "get_function",
    "disassemble_function",
    "disassemble_range",
    "set_decompiler_comment",
    "set_disassembly_comment",
    "set_function_prototype",
    "set_local_variable_type",
    "get_xrefs_to",
    "get_xrefs_from",
    "get_function_xrefs",
    "list_strings",
    "create_struct",
    "add_struct_members",
    "clear_struct",
    "delete_struct",
    "get_struct",
    "list_data_types",
    "get_data_by_label",
    "get_bytes",
    "search_bytes",
    "get_enum",
    "rename_data_type",
    "set_global_data_type",
    "remove_struct_members",
    "set_bytes",
    "get_callee",
    "add_bookmark",
    "list_bookmarks",
    "delete_bookmark",
    "create_function",
    "delete_function",
    "analyze_program",
    "reanalyze_program",
    "bsim_query_target",
    "bsim_query_function",
    "bsim_set_target_metadata",
    "bsim_register_target",
)

INTERNAL_COMMAND_NAMES = (
    "bsim_query_target",
    "bsim_query_function",
    "bsim_register_target",
)

COMMAND_TO_IMPL = {
    "list_functions": list_functions,
    "list_classes": list_classes,
    "decompile_function": decompile_function,
    "rename_function": rename_function,
    "rename_data": rename_data,
    "list_segments": list_segments,
    "list_imports": list_imports,
    "list_exports": list_exports,
    "list_namespaces": list_namespaces,
    "list_data_items": list_data_items,
    "search_functions_by_name": search_functions_by_name,
    "rename_variable": rename_variable,
    "get_function": get_function,
    "disassemble_function": disassemble_function,
    "disassemble_range": disassemble_range,
    "set_decompiler_comment": set_decompiler_comment,
    "set_disassembly_comment": set_disassembly_comment,
    "set_function_prototype": set_function_prototype,
    "set_local_variable_type": set_local_variable_type,
    "get_xrefs_to": get_xrefs_to,
    "get_xrefs_from": get_xrefs_from,
    "get_function_xrefs": get_function_xrefs,
    "list_strings": list_strings,
    "create_struct": create_struct,
    "add_struct_members": add_struct_members,
    "clear_struct": clear_struct,
    "delete_struct": delete_struct,
    "get_struct": get_struct,
    "list_data_types": list_data_types,
    "get_data_by_label": get_data_by_label,
    "get_bytes": get_bytes,
    "search_bytes": search_bytes,
    "get_enum": get_enum,
    "rename_data_type": rename_data_type,
    "set_global_data_type": set_global_data_type,
    "remove_struct_members": remove_struct_members,
    "set_bytes": set_bytes,
    "get_callee": get_callee,
    "add_bookmark": add_bookmark,
    "list_bookmarks": list_bookmarks,
    "delete_bookmark": delete_bookmark,
    "create_function": create_function,
    "delete_function": delete_function,
    "analyze_program": analyze_program,
    "reanalyze_program": reanalyze_program,
    "bsim_query_target": bsim_query_target,
    "bsim_query_function": bsim_query_function,
    "bsim_set_target_metadata": bsim_set_target_metadata,
    "bsim_register_target": bsim_register_target,
}

COMMAND_DEP_KEYS = {
    "list_functions": ("offset", "limit"),
    "list_classes": ("offset", "limit"),
    "decompile_function": ("address", "name"),
    "rename_function": ("address", "oldName", "newName"),
    "rename_data": ("address", "newName"),
    "rename_variable": ("functionName", "oldName", "newName"),
    "list_segments": ("offset", "limit"),
    "list_imports": ("offset", "limit"),
    "list_exports": ("offset", "limit"),
    "list_namespaces": ("offset", "limit"),
    "list_data_items": ("offset", "limit"),
    "search_functions_by_name": ("query", "offset", "limit"),
    "get_function": ("address", "name"),
    "disassemble_function": ("address",),
    "disassemble_range": ("start_address", "end_address", "length", "limit", "address"),
    "set_decompiler_comment": ("address", "comment"),
    "set_disassembly_comment": ("address", "comment"),
    "set_function_prototype": ("function_address", "prototype"),
    "set_local_variable_type": ("function_address", "variable_name", "new_type"),
    "get_xrefs_to": ("address", "offset", "limit"),
    "get_xrefs_from": ("address", "offset", "limit"),
    "get_function_xrefs": ("name", "offset", "limit"),
    "list_strings": ("offset", "limit", "filter"),
    "create_struct": ("name", "size", "category", "members"),
    "add_struct_members": ("struct_name", "members", "category"),
    "clear_struct": ("struct_name", "category"),
    "delete_struct": ("struct_name", "name", "category"),
    "get_struct": ("name", "category"),
    "list_data_types": ("offset", "limit", "filter", "category"),
    "get_data_by_label": ("label",),
    "get_bytes": ("address", "size"),
    "search_bytes": ("bytes", "offset", "limit"),
    "get_enum": ("name", "category"),
    "rename_data_type": ("name", "new_name", "newName", "category"),
    "set_global_data_type": ("address", "data_type", "length", "clear_mode"),
    "remove_struct_members": ("struct_name", "members", "category"),
    "set_bytes": ("address", "bytes"),
    "get_callee": ("address",),
    "add_bookmark": ("address", "category", "comment", "type", "format"),
    "list_bookmarks": ("offset", "limit", "address", "type", "category"),
    "delete_bookmark": ("id", "address", "type", "category", "comment"),
    "create_function": ("address", "name"),
    "delete_function": ("address",),
    "analyze_program": (),
    "reanalyze_program": (),
    "bsim_query_target": (
        "bsim_url",
        "query_target",
        "similarity_threshold",
        "significance_threshold",
        "matches_per_function",
        "max_results",
    ),
    "bsim_query_function": (
        "bsim_url",
        "query_target",
        "address",
        "function_name",
        "similarity_threshold",
        "significance_threshold",
        "matches_per_function",
        "max_results",
    ),
    "bsim_set_target_metadata": ("categories",),
    "bsim_register_target": ("bsim_url", "query_target"),
}

# command -> dependency profile for keyword argument injection into command impl.
COMMAND_PROFILE = {
    "list_functions": ("ensure_context", "to_int", "collect"),
    "list_classes": ("context", "to_int", "iter_namespaces", "safe_call"),
    "decompile_function": ("ensure_context", "get_address", "find_function_by_name", "decompile_function_object"),
    "rename_function": ("ensure_context", "get_address", "find_function_by_name", "txn", "source_type"),
    "rename_data": ("ensure_context", "get_address", "txn", "source_type"),
    "list_segments": ("ensure_context", "to_int"),
    "list_imports": ("ensure_context", "to_int"),
    "list_exports": ("ensure_context", "to_int", "iter_items", "is_exported_symbol"),
    "list_namespaces": ("ensure_context", "to_int", "iter_namespaces", "safe_call"),
    "list_data_items": ("ensure_context", "to_int"),
    "search_functions_by_name": ("ensure_context", "to_int"),
    "rename_variable": (
        "ensure_context",
        "find_function_by_name",
        "decompile_high_function",
        "requires_full_param_commit",
        "high_function_db_util",
        "txn",
        "source_type",
    ),
    "get_function": ("ensure_context", "get_address", "find_function_by_name"),
    "disassemble_function": ("ensure_context", "get_address", "iter_items", "code_unit"),
    "disassemble_range": ("ensure_context", "get_address", "to_int", "iter_items", "code_unit"),
    "set_decompiler_comment": ("ensure_context", "get_address", "txn", "code_unit"),
    "set_disassembly_comment": ("ensure_context", "get_address", "txn", "code_unit"),
    "set_function_prototype": (
        "ensure_context",
        "get_address",
        "build_signature_parser",
        "safe_call",
        "apply_function_signature_cmd",
        "txn",
        "source_type",
    ),
    "set_local_variable_type": (
        "ensure_context",
        "get_address",
        "parse_data_type",
        "decompile_high_function",
        "requires_full_param_commit",
        "high_function_db_util",
        "txn",
        "source_type",
    ),
    "get_xrefs_to": ("ensure_context", "get_address", "to_int", "iter_items"),
    "get_xrefs_from": ("ensure_context", "get_address", "to_int", "iter_items"),
    "get_function_xrefs": ("ensure_context", "find_function_by_name", "to_int", "iter_items"),
    "list_strings": ("ensure_context", "to_int"),
    "create_struct": (
        "ensure_context",
        "to_int",
        "txn",
        "dt_manager",
        "category_path",
        "structure_data_type",
        "parse_data_type",
        "component_length",
        "describe_struct",
    ),
    "add_struct_members": (
        "ensure_context",
        "txn",
        "get_struct_datatype",
        "parse_data_type",
        "component_length",
        "dt_manager",
        "describe_struct",
    ),
    "clear_struct": (
        "ensure_context",
        "txn",
        "get_struct_datatype",
        "safe_call",
        "iter_items",
        "dt_manager",
        "describe_struct",
    ),
    "delete_struct": ("ensure_context", "txn", "get_struct_datatype", "dt_manager", "describe_struct"),
    "get_struct": ("ensure_context", "get_struct_datatype", "describe_struct"),
    "list_data_types": (
        "ensure_context",
        "to_int",
        "dt_manager",
        "collect",
        "iter_items",
        "safe_call",
        "describe_data_type",
    ),
    "get_data_by_label": ("ensure_context", "iter_items"),
    "get_bytes": ("ensure_context", "to_int", "get_address", "hexdump"),
    "search_bytes": ("ensure_context", "to_int", "decode_hex_bytes"),
    "get_enum": ("ensure_context", "get_enum_datatype", "describe_enum", "safe_call"),
    "rename_data_type": (
        "ensure_context",
        "txn",
        "dt_manager",
        "category_path",
        "find_data_type_by_name",
        "describe_data_type",
    ),
    "set_global_data_type": (
        "ensure_context",
        "to_int",
        "get_address",
        "parse_data_type",
        "parse_clear_data_mode",
        "txn",
        "data_utilities",
    ),
    "remove_struct_members": ("ensure_context", "txn", "get_struct_datatype", "dt_manager", "describe_struct"),
    "set_bytes": ("ensure_context", "get_address", "decode_hex_bytes", "txn"),
    "get_callee": ("ensure_context", "get_address", "iter_items", "task_monitor"),
    "add_bookmark": ("ensure_context", "get_address", "txn"),
    "list_bookmarks": ("ensure_context", "get_address", "to_int", "collect", "iter_items"),
    "delete_bookmark": ("ensure_context", "get_address", "txn", "iter_items"),
    "create_function": ("ensure_context", "get_address", "txn"),
    "delete_function": ("ensure_context", "get_address", "txn"),
    "analyze_program": ("ensure_context", "analyze_program_impl"),
    "reanalyze_program": ("ensure_context", "analyze_program_impl"),
    "bsim_query_target": ("ensure_context",),
    "bsim_query_function": ("ensure_context", "get_address", "find_function_by_name"),
    "bsim_set_target_metadata": ("ensure_context", "txn"),
    "bsim_register_target": ("ensure_context",),
}


__all__ = [
    "COMMAND_NAMES",
    "INTERNAL_COMMAND_NAMES",
    "COMMAND_TO_IMPL",
    "COMMAND_DEP_KEYS",
    "COMMAND_PROFILE",
]
