"""Declarative registry for core command shim wiring."""

from __future__ import absolute_import, print_function

from ghidra_headless.handlers.commands import (
    add_bookmark,
    add_class_members,
    add_enum_values,
    add_struct_members,
    clear_struct,
    create_class,
    create_enum,
    create_struct,
    decompile_function,
    decompile_function_by_address,
    disassemble_function,
    get_bytes,
    get_callee,
    get_data_by_label,
    get_enum,
    get_function_by_address,
    get_function_xrefs,
    get_struct,
    get_xrefs_from,
    get_xrefs_to,
    list_classes,
    list_data_items,
    list_exports,
    list_functions,
    list_imports,
    list_methods,
    list_namespaces,
    list_segments,
    list_strings,
    remove_class_members,
    remove_enum_values,
    remove_struct_members,
    rename_data,
    rename_function,
    rename_function_by_address,
    rename_variable,
    search_bytes,
    search_functions_by_name,
    set_bytes,
    set_decompiler_comment,
    set_disassembly_comment,
    set_function_prototype,
    set_global_data_type,
    set_local_variable_type,
)

COMMAND_NAMES = (
    "list_methods",
    "list_functions",
    "list_classes",
    "decompile_function",
    "decompile_function_by_address",
    "rename_function",
    "rename_data",
    "list_segments",
    "list_imports",
    "list_exports",
    "list_namespaces",
    "list_data_items",
    "search_functions_by_name",
    "rename_variable",
    "get_function_by_address",
    "disassemble_function",
    "set_decompiler_comment",
    "rename_function_by_address",
    "set_disassembly_comment",
    "set_function_prototype",
    "set_local_variable_type",
    "get_xrefs_to",
    "get_xrefs_from",
    "get_function_xrefs",
    "list_strings",
    "create_struct",
    "add_struct_members",
    "clear_struct",
    "get_struct",
    "get_data_by_label",
    "get_bytes",
    "search_bytes",
    "create_enum",
    "add_enum_values",
    "get_enum",
    "set_global_data_type",
    "create_class",
    "add_class_members",
    "remove_class_members",
    "remove_enum_values",
    "remove_struct_members",
    "set_bytes",
    "get_callee",
    "add_bookmark",
)

COMMAND_TO_IMPL = {
    "list_methods": list_methods,
    "list_functions": list_functions,
    "list_classes": list_classes,
    "decompile_function": decompile_function,
    "decompile_function_by_address": decompile_function_by_address,
    "rename_function": rename_function,
    "rename_data": rename_data,
    "list_segments": list_segments,
    "list_imports": list_imports,
    "list_exports": list_exports,
    "list_namespaces": list_namespaces,
    "list_data_items": list_data_items,
    "search_functions_by_name": search_functions_by_name,
    "rename_variable": rename_variable,
    "get_function_by_address": get_function_by_address,
    "disassemble_function": disassemble_function,
    "set_decompiler_comment": set_decompiler_comment,
    "rename_function_by_address": rename_function_by_address,
    "set_disassembly_comment": set_disassembly_comment,
    "set_function_prototype": set_function_prototype,
    "set_local_variable_type": set_local_variable_type,
    "get_xrefs_to": get_xrefs_to,
    "get_xrefs_from": get_xrefs_from,
    "get_function_xrefs": get_function_xrefs,
    "list_strings": list_strings,
    "create_struct": create_struct,
    "add_struct_members": add_struct_members,
    "clear_struct": clear_struct,
    "get_struct": get_struct,
    "get_data_by_label": get_data_by_label,
    "get_bytes": get_bytes,
    "search_bytes": search_bytes,
    "create_enum": create_enum,
    "add_enum_values": add_enum_values,
    "get_enum": get_enum,
    "set_global_data_type": set_global_data_type,
    "create_class": create_class,
    "add_class_members": add_class_members,
    "remove_class_members": remove_class_members,
    "remove_enum_values": remove_enum_values,
    "remove_struct_members": remove_struct_members,
    "set_bytes": set_bytes,
    "get_callee": get_callee,
    "add_bookmark": add_bookmark,
}

COMMAND_DEP_KEYS = {
    "list_methods": ("offset", "limit"),
    "list_functions": ("offset", "limit"),
    "list_classes": ("offset", "limit"),
    "decompile_function": ("name",),
    "decompile_function_by_address": ("address",),
    "rename_function": ("oldName", "newName"),
    "rename_function_by_address": ("function_address", "new_name", "newName"),
    "rename_data": ("address", "newName"),
    "rename_variable": ("functionName", "oldName", "newName"),
    "list_segments": ("offset", "limit"),
    "list_imports": ("offset", "limit"),
    "list_exports": ("offset", "limit"),
    "list_namespaces": ("offset", "limit"),
    "list_data_items": ("offset", "limit"),
    "search_functions_by_name": ("query", "offset", "limit"),
    "get_function_by_address": ("address",),
    "disassemble_function": ("address",),
    "set_decompiler_comment": ("address", "comment"),
    "set_disassembly_comment": ("address", "comment"),
    "set_function_prototype": ("function_address", "prototype"),
    "set_local_variable_type": ("function_address", "variable_name", "new_type"),
    "get_xrefs_to": ("address", "offset", "limit"),
    "get_xrefs_from": ("address", "offset", "limit"),
    "get_function_xrefs": ("name", "offset", "limit"),
    "list_strings": ("offset", "limit", "filter"),
    "create_struct": ("name", "size", "category", "members"),
    "add_struct_members": ("struct_name", "members", "category"),
    "clear_struct": ("struct_name", "category"),
    "get_struct": ("name", "category"),
    "get_data_by_label": ("label",),
    "get_bytes": ("address", "size"),
    "search_bytes": ("bytes", "offset", "limit"),
    "create_enum": ("name", "size", "category", "values"),
    "add_enum_values": ("enum_name", "values", "category"),
    "get_enum": ("name", "category"),
    "set_global_data_type": ("address", "data_type", "length", "clear_mode"),
    "create_class": ("name", "parent_namespace", "members"),
    "add_class_members": ("class_name", "members", "parent_namespace"),
    "remove_class_members": ("class_name", "members", "parent_namespace"),
    "remove_enum_values": ("enum_name", "values", "category"),
    "remove_struct_members": ("struct_name", "members", "category"),
    "set_bytes": ("address", "bytes"),
    "get_callee": ("address",),
    "add_bookmark": ("address", "category", "comment", "type", "format"),
}


__all__ = [
    "COMMAND_NAMES",
    "COMMAND_TO_IMPL",
    "COMMAND_DEP_KEYS",
]
