"""Domain-level error contracts."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    OPERATION_FAILED = "OPERATION_FAILED"
    CHECKOUT_REQUIRED = "CHECKOUT_REQUIRED"
    NOT_SHARED_PROJECT = "NOT_SHARED_PROJECT"
    NOT_CHECKED_OUT = "NOT_CHECKED_OUT"
    LOCAL_CHANGES_EXIST = "LOCAL_CHANGES_EXIST"
    UNSAFE_ACTIVE_CHECKOUT_TERMINATE = "UNSAFE_ACTIVE_CHECKOUT_TERMINATE"
    UNSAFE_PROGRAM_REMOVE = "UNSAFE_PROGRAM_REMOVE"
    MERGE_REQUIRED = "MERGE_REQUIRED"
    ADD_TO_VERSION_CONTROL_REQUIRED = "ADD_TO_VERSION_CONTROL_REQUIRED"
    LOCK_TIMEOUT = "LOCK_TIMEOUT"
    TARGET_ALREADY_LOADED = "TARGET_ALREADY_LOADED"
    PROGRAM_ALREADY_IMPORTED = "PROGRAM_ALREADY_IMPORTED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    TARGET_NOT_REGISTERED = "TARGET_NOT_REGISTERED"
    PROGRAM_NOT_FOUND = "PROGRAM_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    REOPEN_FAILED = "REOPEN_FAILED"
    SAVE_FAILED = "SAVE_FAILED"
    SYNC_OPERATION_FAILED = "SYNC_OPERATION_FAILED"
    PROJECT_LOCKED = "PROJECT_LOCKED"
    CORE_EXECUTOR_UNAVAILABLE = "CORE_EXECUTOR_UNAVAILABLE"


@dataclass(slots=True)
class DomainError(Exception):
    code: ErrorCode
    message: str
    hint: str | None = None
    retryable: bool = False
    details: dict[str, Any] | None = None

    def __str__(self) -> str:
        return self.message


__all__ = ["ErrorCode", "DomainError"]
