"""Domain-level error contracts."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    OPERATION_FAILED = "OPERATION_FAILED"
    AMBIGUOUS_FUNCTION = "AMBIGUOUS_FUNCTION"
    AMBIGUOUS_DATA_TYPE = "AMBIGUOUS_DATA_TYPE"
    BSIM_MATCH_STALE = "BSIM_MATCH_STALE"
    CHECKOUT_REQUIRED = "CHECKOUT_REQUIRED"
    CHECKOUT_UNAVAILABLE = "CHECKOUT_UNAVAILABLE"
    HIJACKED_PROGRAM = "HIJACKED_PROGRAM"
    NOT_SHARED_PROJECT = "NOT_SHARED_PROJECT"
    NOT_CHECKED_OUT = "NOT_CHECKED_OUT"
    LOCAL_CHANGES_EXIST = "LOCAL_CHANGES_EXIST"
    UNSAFE_ACTIVE_CHECKOUT_TERMINATE = "UNSAFE_ACTIVE_CHECKOUT_TERMINATE"
    UNSAFE_VERSIONED_DELETE = "UNSAFE_VERSIONED_DELETE"
    UNSAFE_PROGRAM_REMOVE = "UNSAFE_PROGRAM_REMOVE"
    MERGE_REQUIRED = "MERGE_REQUIRED"
    ADD_TO_VERSION_CONTROL_REQUIRED = "ADD_TO_VERSION_CONTROL_REQUIRED"
    LOCK_TIMEOUT = "LOCK_TIMEOUT"
    TARGET_ALREADY_LOADED = "TARGET_ALREADY_LOADED"
    PROGRAM_ALREADY_IMPORTED = "PROGRAM_ALREADY_IMPORTED"
    REQUEST_ID_CONFLICT = "REQUEST_ID_CONFLICT"
    RESULT_DISCARDED = "RESULT_DISCARDED"
    IMPORT_IN_PROGRESS = "IMPORT_IN_PROGRESS"
    ANALYSIS_IN_PROGRESS = "ANALYSIS_IN_PROGRESS"
    IMPORT_OUTPUT_UNCERTAIN = "IMPORT_OUTPUT_UNCERTAIN"
    OPERATION_QUEUE_FULL = "OPERATION_QUEUE_FULL"
    OPERATION_NOT_FOUND = "OPERATION_NOT_FOUND"
    OPERATION_WORKER_UNAVAILABLE = "OPERATION_WORKER_UNAVAILABLE"
    OPERATION_WORKER_FAILED = "OPERATION_WORKER_FAILED"
    OPERATION_SHUTDOWN = "OPERATION_SHUTDOWN"
    OPERATION_CANCELLED = "OPERATION_CANCELLED"
    TARGET_REBOUND = "TARGET_REBOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    TARGET_NOT_REGISTERED = "TARGET_NOT_REGISTERED"
    PROGRAM_NOT_FOUND = "PROGRAM_NOT_FOUND"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    REOPEN_FAILED = "REOPEN_FAILED"
    SAVE_FAILED = "SAVE_FAILED"
    SYNC_OPERATION_FAILED = "SYNC_OPERATION_FAILED"
    PROJECT_LOCKED = "PROJECT_LOCKED"
    CORE_EXECUTOR_UNAVAILABLE = "CORE_EXECUTOR_UNAVAILABLE"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    CHECKOUT_NOT_FOUND = "CHECKOUT_NOT_FOUND"
    SHARED_PROJECT_UNAVAILABLE = "SHARED_PROJECT_UNAVAILABLE"
    PRIVATE_FILE_DELETE_NOT_ALLOWED = "PRIVATE_FILE_DELETE_NOT_ALLOWED"
    SHARED_FILE_DELETE_BLOCKED = "SHARED_FILE_DELETE_BLOCKED"
    LATEST_VERSION_MISMATCH = "LATEST_VERSION_MISMATCH"
    ADD_TO_VERSION_CONTROL_NOT_ALLOWED = "ADD_TO_VERSION_CONTROL_NOT_ALLOWED"
    CHECKIN_NOT_ALLOWED = "CHECKIN_NOT_ALLOWED"
    KEEP_FILE_NOT_FOUND = "KEEP_FILE_NOT_FOUND"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    VERSION_DIFF_TIMEOUT = "VERSION_DIFF_TIMEOUT"
    PROGRAM_NOT_OPEN = "PROGRAM_NOT_OPEN"
    PROGRAM_OPEN_FAILED = "PROGRAM_OPEN_FAILED"
    IMPORT_FAILED = "IMPORT_FAILED"
    SESSION_CLOSE_FAILED = "SESSION_CLOSE_FAILED"
    PROGRAM_CLOSE_FAILED = "PROGRAM_CLOSE_FAILED"
    REMOVE_PROGRAM_FAILED = "REMOVE_PROGRAM_FAILED"
    PROJECT_CLOSE_FAILED = "PROJECT_CLOSE_FAILED"
    PROJECT_ALREADY_EXISTS = "PROJECT_ALREADY_EXISTS"
    PROJECT_IN_USE = "PROJECT_IN_USE"
    SESSION_CHANGED = "SESSION_CHANGED"
    HEADLESS_UNSUPPORTED = "HEADLESS_UNSUPPORTED"
    JVM_NOT_HEADLESS = "JVM_NOT_HEADLESS"
    # The Ghidra GUI backend (--backend gui): an operation or argument it does not offer,
    # and a display that succeeded while moving to the location did not.
    GUI_UNSUPPORTED = "GUI_UNSUPPORTED"
    GUI_NAVIGATION_FAILED = "GUI_NAVIGATION_FAILED"
    READ_ONLY_PROGRAM = "READ_ONLY_PROGRAM"
    PROGRAM_NOT_ANALYZED = "PROGRAM_NOT_ANALYZED"
    RAW_LOADER_OPTION_UNAVAILABLE = "RAW_LOADER_OPTION_UNAVAILABLE"
    # Ghidra script execution (scripts category)
    SCRIPTS_DISABLED = "SCRIPTS_DISABLED"
    SCRIPT_NOT_FOUND = "SCRIPT_NOT_FOUND"
    AMBIGUOUS_SCRIPT = "AMBIGUOUS_SCRIPT"
    SCRIPT_RUNTIME_AMBIGUOUS = "SCRIPT_RUNTIME_AMBIGUOUS"
    SCRIPT_RUNTIME_UNAVAILABLE = "SCRIPT_RUNTIME_UNAVAILABLE"
    SCRIPT_COMPILE_FAILED = "SCRIPT_COMPILE_FAILED"
    SCRIPT_LOAD_FAILED = "SCRIPT_LOAD_FAILED"
    SCRIPT_FAILED = "SCRIPT_FAILED"
    SCRIPT_TIMEOUT = "SCRIPT_TIMEOUT"
    SCRIPT_CANCELLED = "SCRIPT_CANCELLED"
    TARGET_EXECUTION_INVALID = "TARGET_EXECUTION_INVALID"
    TARGET_ORPHAN_UNRELEASED = "TARGET_ORPHAN_UNRELEASED"
    RUNTIME_DEGRADED = "RUNTIME_DEGRADED"
    # The background startup (JVM, Ghidra, startup sessions) failed after serving began.
    STARTUP_FAILED = "STARTUP_FAILED"
    # BSim tools (bsim category).  Each message starts with its code, as
    # "BSIM_...: detail"; BSIM_MATCH_STALE is above.
    BSIM_ADD_EXECUTABLE_CATEGORY_FAILED = "BSIM_ADD_EXECUTABLE_CATEGORY_FAILED"
    BSIM_ALREADY_REGISTERED = "BSIM_ALREADY_REGISTERED"
    BSIM_APPLY_MATCHES_FAILED = "BSIM_APPLY_MATCHES_FAILED"
    BSIM_AUTHENTICATION_FAILED = "BSIM_AUTHENTICATION_FAILED"
    BSIM_CLI_FAILED = "BSIM_CLI_FAILED"
    BSIM_DATABASE_INIT_FAILED = "BSIM_DATABASE_INIT_FAILED"
    BSIM_DATABASE_STATUS_FAILED = "BSIM_DATABASE_STATUS_FAILED"
    BSIM_DATABASE_UNREACHABLE = "BSIM_DATABASE_UNREACHABLE"
    BSIM_DELETE_CONFIRMATION_MISMATCH = "BSIM_DELETE_CONFIRMATION_MISMATCH"
    BSIM_DELETE_EXECUTABLE_FAILED = "BSIM_DELETE_EXECUTABLE_FAILED"
    BSIM_EXECUTABLE_AMBIGUOUS = "BSIM_EXECUTABLE_AMBIGUOUS"
    BSIM_EXECUTABLE_CATEGORY_INVALID = "BSIM_EXECUTABLE_CATEGORY_INVALID"
    BSIM_EXECUTABLE_CATEGORY_NOT_CONFIGURED = "BSIM_EXECUTABLE_CATEGORY_NOT_CONFIGURED"
    BSIM_EXECUTABLE_LOOKUP_INVALID = "BSIM_EXECUTABLE_LOOKUP_INVALID"
    BSIM_EXECUTABLE_LOOKUP_REQUIRED = "BSIM_EXECUTABLE_LOOKUP_REQUIRED"
    BSIM_EXECUTABLE_LOOKUP_TRUNCATED = "BSIM_EXECUTABLE_LOOKUP_TRUNCATED"
    BSIM_EXECUTABLE_METADATA_INVALID = "BSIM_EXECUTABLE_METADATA_INVALID"
    BSIM_EXECUTABLE_NOT_FOUND = "BSIM_EXECUTABLE_NOT_FOUND"
    BSIM_EXECUTABLE_UPDATE_UNSUPPORTED = "BSIM_EXECUTABLE_UPDATE_UNSUPPORTED"
    BSIM_FUNCTION_NOT_FOUND = "BSIM_FUNCTION_NOT_FOUND"
    BSIM_GET_EXECUTABLE_FAILED = "BSIM_GET_EXECUTABLE_FAILED"
    BSIM_GHIDRA_VERSION_FAILED = "BSIM_GHIDRA_VERSION_FAILED"
    BSIM_INSERT_FAILED = "BSIM_INSERT_FAILED"
    BSIM_INVALID_MATCHED_REF = "BSIM_INVALID_MATCHED_REF"
    BSIM_LIST_CATEGORIES_FAILED = "BSIM_LIST_CATEGORIES_FAILED"
    BSIM_LIST_EXECUTABLES_FAILED = "BSIM_LIST_EXECUTABLES_FAILED"
    BSIM_NO_FUNCTIONS = "BSIM_NO_FUNCTIONS"
    BSIM_OPERATION_FAILED = "BSIM_OPERATION_FAILED"
    BSIM_PARAMETER_INVALID = "BSIM_PARAMETER_INVALID"
    BSIM_PASSWORD_CONFIG_INVALID = "BSIM_PASSWORD_CONFIG_INVALID"  # noqa: S105 - an error code, not a secret
    BSIM_QUERY_FAILED = "BSIM_QUERY_FAILED"
    BSIM_REGISTER_FAILED = "BSIM_REGISTER_FAILED"
    BSIM_REMOTE_PROJECT_LOAD_UNSUPPORTED = "BSIM_REMOTE_PROJECT_LOAD_UNSUPPORTED"
    BSIM_TARGET_METADATA_INVALID = "BSIM_TARGET_METADATA_INVALID"
    BSIM_UNSAVED_PROGRAM = "BSIM_UNSAVED_PROGRAM"
    BSIM_UPDATE_EXECUTABLE_METADATA_FAILED = "BSIM_UPDATE_EXECUTABLE_METADATA_FAILED"
    BSIM_UPDATE_FAILED = "BSIM_UPDATE_FAILED"
    BSIM_URL_INVALID = "BSIM_URL_INVALID"
    BSIM_URL_REQUIRED = "BSIM_URL_REQUIRED"


@dataclass(slots=True)
class DomainError(Exception):
    code: ErrorCode
    message: str
    hint: str | None = None
    retryable: bool = False
    details: dict[str, Any] | None = None

    def __str__(self) -> str:
        return self.message


__all__ = ["ErrorCode", "DomainError"]
