"""Domain-level error contracts."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    OPERATION_FAILED = "OPERATION_FAILED"
    CHECKOUT_REQUIRED = "CHECKOUT_REQUIRED"
    CHECKOUT_UNAVAILABLE = "CHECKOUT_UNAVAILABLE"
    HIJACKED_PROGRAM = "HIJACKED_PROGRAM"
    NOT_SHARED_PROJECT = "NOT_SHARED_PROJECT"
    NOT_CHECKED_OUT = "NOT_CHECKED_OUT"
    LOCAL_CHANGES_EXIST = "LOCAL_CHANGES_EXIST"
    UNSAFE_ACTIVE_CHECKOUT_TERMINATE = "UNSAFE_ACTIVE_CHECKOUT_TERMINATE"
    UNSAFE_VERSIONED_DELETE = "UNSAFE_VERSIONED_DELETE"
    UNSAFE_PROGRAM_REMOVE = "UNSAFE_PROGRAM_REMOVE"
    MERGE_REQUIRED = "MERGE_REQUIRED"
    ADD_TO_VERSION_CONTROL_REQUIRED = "ADD_TO_VERSION_CONTROL_REQUIRED"
    LOCK_TIMEOUT = "LOCK_TIMEOUT"
    TARGET_ALREADY_LOADED = "TARGET_ALREADY_LOADED"
    PROGRAM_ALREADY_IMPORTED = "PROGRAM_ALREADY_IMPORTED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    TARGET_NOT_REGISTERED = "TARGET_NOT_REGISTERED"
    PROGRAM_NOT_FOUND = "PROGRAM_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    REOPEN_FAILED = "REOPEN_FAILED"
    SAVE_FAILED = "SAVE_FAILED"
    SYNC_OPERATION_FAILED = "SYNC_OPERATION_FAILED"
    PROJECT_LOCKED = "PROJECT_LOCKED"
    CORE_EXECUTOR_UNAVAILABLE = "CORE_EXECUTOR_UNAVAILABLE"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    CHECKOUT_NOT_FOUND = "CHECKOUT_NOT_FOUND"
    SHARED_PROJECT_UNAVAILABLE = "SHARED_PROJECT_UNAVAILABLE"
    PRIVATE_FILE_DELETE_NOT_ALLOWED = "PRIVATE_FILE_DELETE_NOT_ALLOWED"
    SHARED_FILE_DELETE_BLOCKED = "SHARED_FILE_DELETE_BLOCKED"
    LATEST_VERSION_MISMATCH = "LATEST_VERSION_MISMATCH"
    ADD_TO_VERSION_CONTROL_NOT_ALLOWED = "ADD_TO_VERSION_CONTROL_NOT_ALLOWED"
    CHECKIN_NOT_ALLOWED = "CHECKIN_NOT_ALLOWED"
    KEEP_FILE_NOT_FOUND = "KEEP_FILE_NOT_FOUND"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    VERSION_DIFF_TIMEOUT = "VERSION_DIFF_TIMEOUT"
    PROGRAM_NOT_OPEN = "PROGRAM_NOT_OPEN"
    PROGRAM_OPEN_FAILED = "PROGRAM_OPEN_FAILED"
    IMPORT_FAILED = "IMPORT_FAILED"
    SESSION_CLOSE_FAILED = "SESSION_CLOSE_FAILED"
    PROGRAM_CLOSE_FAILED = "PROGRAM_CLOSE_FAILED"
    REMOVE_PROGRAM_FAILED = "REMOVE_PROGRAM_FAILED"
    PROJECT_CLOSE_FAILED = "PROJECT_CLOSE_FAILED"
    PROJECT_ALREADY_EXISTS = "PROJECT_ALREADY_EXISTS"
    PROJECT_IN_USE = "PROJECT_IN_USE"
    SESSION_CHANGED = "SESSION_CHANGED"
    HEADLESS_UNSUPPORTED = "HEADLESS_UNSUPPORTED"
    JVM_NOT_HEADLESS = "JVM_NOT_HEADLESS"
    READ_ONLY_PROGRAM = "READ_ONLY_PROGRAM"


@dataclass(slots=True)
class DomainError(Exception):
    code: ErrorCode
    message: str
    hint: str | None = None
    retryable: bool = False
    details: dict[str, Any] | None = None

    def __str__(self) -> str:
        return self.message


__all__ = ["ErrorCode", "DomainError"]
