"""Explicit short tool descriptions; full documentation remains authoritative."""

SHORT_TOOL_DESCRIPTIONS = {
    "batch_read": "Read 1-20 independent queries on one target. Check item statuses; large results use one result_id with /items indexing.",
    "list_targets": "List registered targets and their state, including project info and whether a program is loaded (domain_path).",
    "create_project": "Create an empty local Ghidra project.",
    "open_program": "Open an existing project program in a new target; use register_target before importing a new binary.",
    "register_target": "Register a target with project information only, without loading a program yet.",
    "close_session": "Close a target's program session.",
    "close_session_and_remove_program": "Close a target's session and delete the program from the project.",
    "list_project_programs": "List the programs in the target's project with their domain paths and shared-project sync summary.",
    "import_program": "Import a binary, Ghidra archive (.gzf), or raw binary / shellcode into the current target's project.",
    "load_project_program": "Load or switch a program for an existing target by domain path.",
    "save_project_program": "Persist the currently loaded program for a target into its Ghidra project.",
    "get_program_info": "Get loaded-program identity, language, ranges, counts, analysis and unsaved/undo state.",
    "undo_program_change": "Undo the most recent count transactions on the loaded program (each mutating tool call is one transaction).",
    "redo_program_change": "Redo up to count transactions undone by undo_program_change.",
    "export_program": "Write the loaded program to output_path as a Ghidra .gzf archive (format='gzf', the saved state including analysis) or as the raw bytes of its initialized memory (format='binary').",
    "list_scripts": "List the Ghidra scripts the operator made executable (script_id = '<root>:<relative path>').",
    "get_script_info": "Inspect catalog script metadata and optionally source before run_script.",
    "run_script": "Run catalog script_id or inline source on the loaded program. Mutates state; inspect transaction_outcome on failure.",
    "get_bsim_database_status": "Get BSim database metadata: executable count, configured executable categories, function tags, and backend/server details.",
    "bsim_add_executable_category": "Add a user-defined executable metadata category to the BSim database.",
    "list_bsim_executables": "List BSim executable records with optional filters.",
    "get_bsim_executable": "Get one BSim executable record by md5 or executable name.",
    "bsim_update_executable_metadata": "Update executable metadata categories on an existing BSim executable record looked up by md5 or executable name.",
    "bsim_load_matched_executable": "Load the executable referenced by a BSim matched_ref into a reusable target.",
    "bsim_register_target": "Generate signatures for the loaded target program and insert them into the BSim database.",
    "bsim_apply_matches": "Query the BSim database for the loaded program's functions and rename each one after its best match, all in one transaction.",
    "bsim_update_target_signatures": "Push the loaded program's current function names and metadata back to its existing BSim records (Ghidra's generateupdates + commitupdates in one step).",
    "bsim_delete_executable": "Delete one executable and all of its function records from the BSim database, looked up by md5 or exact executable name.",
    "list_functions": "List functions of the loaded program with name, entry, body size, and is_thunk (paginated).",
    "list_namespaces": "List namespaces of the loaded program as {name, is_class} (paginated); classes_only=true returns only class namespaces.",
    "decompile_function": "Return C-like pseudocode for a function by address or name (address wins if both are set).",
    "create_function": "Create a function at an address, disassembling it first when needed.",
    "delete_function": "Delete the function at or containing the address.",
    "analyze_program": "Run Ghidra auto-analysis if the program has not been analyzed yet; force=true runs it again on an already analyzed program.",
    "get_function": "Get function signature, variables, body, thunk and comments by address or unique name; address wins.",
    "list_segments": "List memory blocks with start, end, length, and read/write/execute permissions (paginated).",
    "list_imports": "List imported (external) symbols of the loaded program as {name, library, full_name, address} (paginated).",
    "list_exports": "List exported symbols and external entry points as {name, address} (paginated).",
    "list_data_items": "List defined data items with address, data type, label, length, and value (paginated).",
    "list_strings": "List defined strings with addresses, optionally filtered by a case-insensitive substring (paginated, default limit 2000).",
    "get_data_by_label": "Return defined data items whose symbol matches the label, with their value representation.",
    "list_data_types": "List data types in the program's data type manager, optionally filtered by name substring or category path (paginated).",
    "get_bytes": "Return a hex dump of size bytes starting at address (1 to 1,048,576 bytes).",
    "search_bytes": "Find occurrences of a hex byte pattern in memory and return their addresses (paginated).",
    "set_function_prototype": "Apply a C prototype string to the function given by function_address or function_name (address wins), replacing its signature.",
    "set_local_variable_type": "Set the data type of a local variable or parameter by name in the function given by function_address or function_name (address wins).",
    "set_global_data_type": "Apply a data type at an address; clear_mode controls how conflicting existing data is cleared (default CHECK_FOR_SPACE).",
    "set_bytes": "Overwrite memory at address with the given hex bytes (up to 1 MiB).",
    "get_comments": "Return the pre, eol, post, plate, and repeatable comments at an address (null when unset).",
    "search_symbols": "Search all symbol names by substring or * / ? glob, case-insensitively.",
    "create_label": "Create a user-defined label at an address, even where no symbol exists yet; rename_data only renames existing symbols.",
    "add_bookmark": "Add a bookmark of the given type and category at an address.",
    "list_bookmarks": "List bookmarks, optionally filtered by address, type, and category (paginated).",
    "delete_bookmark": "Delete bookmarks by id, or by address plus type and category (optionally matching comment).",
    "create_struct": "Create a structure data type; members is a list of {name, type, comment?, offset?} objects.",
    "add_struct_members": "Append or place members ({name, type, comment?, offset?}); explicit offsets disable packing and preserve other member positions. Omitted offsets append using current layout.",
    "delete_data_type": "Delete a data type (structure, union, enum, typedef, ...) from the program's data type manager, found by name and optionally category.",
    "remove_struct_members": "Remove selected structure members; empty members is a no-op, clear_all explicitly removes all.",
    "rename_data_type": "Rename a data type found by name (optionally within a category).",
    "create_enum": "Create an enum data type of size 1, 2, 4, or 8 bytes; values maps each name to an integer (or to {value, comment}); hex strings such as '0x10' are accepted.",
    "set_enum_values": "Add or replace named values on an existing enum and/or remove names listed in remove; at least one of values or remove is required.",
    "parse_c_declarations": "Parse C declarations (structs, unions, enums, typedefs, function prototypes) with Ghidra's C parser and add the resulting data types to the program.",
    "get_project_sync_status": "Get shared-project version-control status for the target program",
    "get_version_history": "Get version history metadata for the target program in a shared project",
    "get_version_diff": "Get a summary of differences between two shared-project versions of the target program: counts, difference types, and address ranges.",
    "checkout_project_program": "Checkout the target program in a shared project.",
    "add_project_program_to_version_control": "Add the target program to shared-project version control",
    "commit_project_program": "Check-in changes of the target program to the shared project server.",
    "pull_project_program": "Follow the latest repository version of the target program.",
    "undo_checkout_project_program": "Undo checkout for the target program (optionally discard local changes)",
    "terminate_project_program_checkout": "Terminate a stale checkout by checkout id for the target program",
    "delete_shared_project_file": "Delete a project file that no target has loaded, after confirmation and checkout safety checks; versioned deletion requires an explicit non-atomic-risk acknowledgement.",
    "get_xrefs": "Read references to/from an address with endpoint functions; cursor pages share a program revision.",
    "get_call_edges": "Read incoming/outgoing function calls, including optional tail calls and unresolved edges; accepts address or unique name.",
    "disassemble": "Read existing instructions for a function OR address range; cursor resumes within the same program revision.",
    "get_data_type": "Describe a data type by full path (preferred) or unique name.",
    "apply_edits": "Apply 1-100 ordered renames, prototypes, types or comments. rename_function accepts new_name and/or namespace_path; create_namespace creates missing parents.",
    "bsim_query": "Search BSim with scope=program or functions; function scope requires address/name selectors. Returns matched_ref.",
}
